In [25]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

**Load dataset/csv file**

In [26]:
df=pd.read_csv("/content/drive/MyDrive/Mall_Customers.csv")

In [27]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [29]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

 **Identify and handle missing values using .isnull()**

In [30]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

**Drop rows with nulls**

In [31]:
df.dropna(inplace=True)

**Check for duplicates**

In [32]:
f'Duplicates: {df.duplicated().sum()}'

'Duplicates: 0'

**Remove duplicate rows using .drop_duplicates()**
as we do not have any duplicates we dont consider this step

In [33]:
df.drop_duplicates(inplace=True)

**Standardize text values**

In [34]:
df['Gender'] = df['Gender'].str.strip().str.lower()

In [35]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    male   19                  15                      39
1             2    male   21                  15                      81
2             3  female   20                  16                       6
3             4  female   23                  16                      77
4             5  female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  female   35                 120                      79
196         197  female   45                 126                      28
197         198    male   32                 126                      74
198         199    male   32                 137                      18
199         200    male   30                 137                      83

[200 rows x 5 columns]

**Rename column headers**

In [36]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [44]:
df

     customerid  gender  age  annual_income_(k$)  spending_score_(1-100)
0             1    male   19                  15                      39
1             2    male   21                  15                      81
2             3  female   20                  16                       6
3             4  female   23                  16                      77
4             5  female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  female   35                 120                      79
196         197  female   45                 126                      28
197         198    male   32                 126                      74
198         199    male   32                 137                      18
199         200    male   30                 137                      83

[200 rows x 5 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerid              200 non-null    int64
 1   gender                  200 non-null    object
 2   age                     200 non-null    int64
 3   annual_income_(k$)      200 non-null    int64
 4   spending_score_(1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

**Check and fix data types**

In [41]:
df['gender'] = df['gender'].astype('category')

In [42]:
df

     customerid  gender  age  annual_income_(k$)  spending_score_(1-100)
0             1    male   19                  15                      39
1             2    male   21                  15                      81
2             3  female   20                  16                       6
3             4  female   23                  16                      77
4             5  female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  female   35                 120                      79
196         197  female   45                 126                      28
197         198    male   32                 126                      74
198         199    male   32                 137                      18
199         200    male   30                 137                      83

[200 rows x 5 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerid              200 non-null    int64
 1   gender                  200 non-null    category
 2   age                     200 non-null    int64
 3   annual_income_(k$)      200 non-null    int64
 4   spending_score_(1-100)  200 non-null    int64
dtypes: category(1), int64(4)
memory usage: 6.7 KB